# -*- coding: utf-8 -*-
"""graduation_project(embeddings converter).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GNey3apHca0UV9zGtxbmwBMQjHYYaqck
"""

!pip install sentence-transformers faiss-cpu -q
!pip install chardet -q
!pip install pdfplumber -q

from google.colab import files

uploaded = files.upload()
print("✅ File uploaded!")

import pdfplumber
import json
import re

def clean_text(text):
    if not text:
        return ""
    text = text.lower()
    text = re.sub(r"[•▪▸►●◆◇→\-–—]+", " ", text)
    text = re.sub(r"[^\w\s\u0600-\u06FF.,!?]", " ", text)
    text = re.sub(r"\s+", " ", text)
    return text.strip()

filename = list(uploaded.keys())[0]
slides = []

with pdfplumber.open(filename) as pdf:
    for page_num, page in enumerate(pdf.pages, start=1):
        raw_text = page.extract_text()
        cleaned = clean_text(raw_text) if raw_text else ""
        slides.append({
            "slide_id": page_num,
            "content": cleaned
        })

print(f"✅ Loaded {len(slides)} slides")
print("Example:", slides[0])

#used the first model
from sentence_transformers import SentenceTransformer

model = SentenceTransformer("all-mpnet-base-v2")  # upgraded model for better accuracy

texts = [slide["content"] for slide in slides]
embeddings = model.encode(texts, show_progress_bar=True)

print(f"✅ Shape: {embeddings.shape}")

import faiss
import numpy as np
embeddings_np = np.array(embeddings).astype("float32")

# normalize to use Cosine Similarity
faiss.normalize_L2(embeddings_np)

dimension = embeddings_np.shape[1]
index = faiss.IndexFlatIP(dimension)  # IP = Cosine Similarity
index.add(embeddings_np)

print(f"✅ FAISS index ready!")
print(f"✅ Total vectors stored: {index.ntotal}")

# this is for spelling correction
!pip install textblob -q

from textblob import TextBlob
from sentence_transformers import SentenceTransformer
import numpy as np
import faiss

# ─────────────────────────────────────────────
# Spell correction function
# ─────────────────────────────────────────────
TECHNICAL_TERMS = {
    "NaN", "null", "None", "True", "False", "API", "JSON", "PDF",
    "EDA", "ML", "AI", "KYD", "VOC", "ABA", "SQL", "CSV", "URL",
    "HTTP", "HTTPS", "DataFrame", "numpy", "pandas", "sklearn"
}

def correct_spelling(text):
    import re
    masked = text
    placeholders = {}
    for i, term in enumerate(TECHNICAL_TERMS):
        placeholder = f"ZZZTECHZZZ{i}ZZZ"
        placeholders[placeholder] = term
        masked = re.sub(rf'\b{term}\b', placeholder, masked, flags=re.IGNORECASE)
    corrected = str(TextBlob(masked).correct())
    for placeholder, term in placeholders.items():
        corrected = corrected.replace(placeholder, term)
    return corrected

# ─────────────────────────────────────────────
# Test questions and ground truth
# ─────────────────────────────────────────────
test_questions = [
    "what is KYD?",
    "what are the data soureces that are included or i can use?",
    "why do i need to understand the i the data?",
]

ground_truth = [3, 7, 8]  # correct slide for each question

# ─────────────────────────────────────────────
# Run spell correction on all questions
# ─────────────────────────────────────────────
print("🔤 Spell Correction Results:")
print("─" * 50)
corrected_questions = []
for q in test_questions:
    corrected = correct_spelling(q)
    corrected_questions.append(corrected)
    print()

# ─────────────────────────────────────────────
# Encode corrected questions
# ─────────────────────────────────────────────
question_embeddings = model.encode(corrected_questions)
question_embeddings_np = np.array(question_embeddings).astype("float32")
faiss.normalize_L2(question_embeddings_np)

# ─────────────────────────────────────────────
# Search FAISS and evaluate
# ─────────────────────────────────────────────
print("🔍 Search Results:")
print("─" * 50)

correct_top1 = 0
correct_top3 = 0

for i, q_emb in enumerate(question_embeddings_np):
    q_emb_np = np.array([q_emb]).astype("float32")

    # Search top 3 closest slides
    distances, indices = index.search(q_emb_np, k=3)

    top1_slide = slides[indices[0][0]]["slide_id"]
    top3_slides = [slides[idx]["slide_id"] for idx in indices[0]]
    actual = ground_truth[i]

    top1_correct = top1_slide == actual
    top3_correct = actual in top3_slides

    if top1_correct:
        correct_top1 += 1
    if top3_correct:
        correct_top3 += 1

    status = "✅" if top1_correct else "❌"
    print(f"{status} Q: {test_questions[i]}")
    print(f"   Top-1 : Slide {top1_slide} | Actual: Slide {actual}")
    print(f"   Top-3 : {top3_slides}\n")

# ─────────────────────────────────────────────
# Final accuracy
# ─────────────────────────────────────────────
total = len(test_questions)
top1_acc = correct_top1 / total * 100
top3_acc = correct_top3 / total * 100

print("─" * 50)
print(f"🎯 Top-1 Accuracy: {top1_acc:.1f}%")
print(f"🎯 Top-3 Accuracy: {top3_acc:.1f}%")

# Show improvement
print("─" * 50)
print(f"📈 Before spell correction: 66.7%")
print(f"📈 After spell correction : {top1_acc:.1f}%")

#questions generator
!pip install groq -q

from groq import Groq
import json

# ─────────────────────────────────────────────
# Setup Groq client (free API)
# ─────────────────────────────────────────────
# Read API key from file
api_key = "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"
client = Groq(api_key=api_key)


# ─────────────────────────────────────────────
# Generate 50 questions from slides
# ─────────────────────────────────────────────
all_questions = []

for slide in slides:
    if not slide["content"].strip():
        continue

    prompt = f"""
You are a student who is studying the following slide content:

Slide {slide['slide_id']}: {slide['content']}

Generate 5 realistic student questions about this slide.
- Some questions should be clear and direct
- Some should have spelling mistakes
- Some should be confused/indirect

Return ONLY a JSON array like this:
[
  {{"question": "...", "slide_id": {slide['slide_id']}}},
  ...
]
No extra text, just the JSON.
"""

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",# note i changed the model is was  llama3-8b-8192
        messages=[{"role": "user", "content": prompt}]
    )

    text = response.choices[0].message.content
    # Clean and parse JSON
    text = text.strip().replace("```json", "").replace("```", "")
    questions = json.loads(text)
    all_questions.extend(questions)

print(f"✅ Generated {len(all_questions)} questions!")
print("Example:", all_questions[0])

# ─────────────────────────────────────────────
# Test model accuracy on all 50 generated questions
# ─────────────────────────────────────────────
correct_top1 = 0
correct_top3 = 0
total = len(all_questions)

for item in all_questions:
    question = item["question"]
    actual_slide = item["slide_id"]

    # Spell correction
    corrected = str(TextBlob(question).correct())

    # Encode question
    q_emb = model.encode([corrected])
    q_emb_np = np.array(q_emb).astype("float32")
    faiss.normalize_L2(q_emb_np)

    # Search FAISS
    distances, indices = index.search(q_emb_np, k=3)

    top1_slide = slides[indices[0][0]]["slide_id"]
    top3_slides = [slides[idx]["slide_id"] for idx in indices[0]]

    if top1_slide == actual_slide:
        correct_top1 += 1
    if actual_slide in top3_slides:
        correct_top3 += 1

# ─────────────────────────────────────────────
# Results
# ─────────────────────────────────────────────
print(f"📊 Total questions tested: {total}")
print(f"🎯 Top-1 Accuracy: {correct_top1/total*100:.1f}%")
print(f"🎯 Top-3 Accuracy: {correct_top3/total*100:.1f}%")



# ═════════════════════════════════════════════════════════════════
# LLM ANSWER GENERATION & EVALUATION
# ═════════════════════════════════════════════════════════════════

llm_models = [
    "llama-3.3-70b-versatile",
    "llama-3.1-8b-instant",
    "openai/gpt-oss-20b",
]

# ─────────────────────────────────────────────
# Function: Query Expansion
# LLM rewrites question with technical keywords
# ─────────────────────────────────────────────
def expand_query(question):
    try:
        prompt = f"""Rewrite this student question using technical keywords that would appear in lecture slides.
Return ONLY the rewritten question, nothing else. Keep it short (max 20 words).

Question: {question}
Rewritten:"""
        response = client.chat.completions.create(
            model="llama-3.1-8b-instant",
            messages=[{"role": "user", "content": prompt}],
            max_tokens=40,
        )
        return response.choices[0].message.content.strip()
    except:
        return question

# ─────────────────────────────────────────────
# Function: Adaptive Retrieval with Query Expansion
# k depends on document size for better accuracy
# ─────────────────────────────────────────────
def retrieve_best_slide(question):
    # Step 1: spell correction + query expansion
    corrected = correct_spelling(question)
    expanded = expand_query(corrected)

    # Step 2: encode expanded query
    q_emb = model.encode([expanded])
    q_emb_np = np.array(q_emb).astype("float32")
    faiss.normalize_L2(q_emb_np)

    # Adaptive k based on number of slides
    n = len(slides)
    if n <= 50:
        k = 1   # small doc → top-1 is enough
    elif n <= 100:
        k = 3   # medium doc → top-3
    else:
        k = 5   # large doc → top-5

    k = min(k, n)
    distances, indices = index.search(q_emb_np, k=k)
    top_slides = [slides[i] for i in indices[0]]

    # if k=1 return directly, no need for LLM to pick
    if k == 1:
        return top_slides[0]

    slides_text = "\n\n".join([
        f"Slide {s['slide_id']}: {s['content'][:300]}"
        for s in top_slides
    ])

    pick_prompt = f"""You are given {k} slides and a student question.
Pick the ONE slide that best answers the question.
Return ONLY the slide number as a single integer, nothing else.

{slides_text}

Question: {question}
Best slide number:"""

    response = client.chat.completions.create(
        model="llama-3.1-8b-instant",
        messages=[{"role": "user", "content": pick_prompt}],
        max_tokens=5,
    )

    try:
        best_id = int(response.choices[0].message.content.strip())
        result = next((s for s in top_slides if s["slide_id"] == best_id), top_slides[0])
    except:
        result = top_slides[0]

    return result

# ─────────────────────────────────────────────
# Function: get LLM answer
# ─────────────────────────────────────────────
def get_llm_answer(question, slide_content, llm_model_name):
    prompt = f"""You are a helpful teaching assistant.
Slide content: {slide_content}
Student question: {question}
Answer based ONLY on the slide content. Be concise."""
    response = client.chat.completions.create(
        model=llm_model_name,
        messages=[{"role": "user", "content": prompt}],
        max_tokens=300,
    )
    return response.choices[0].message.content.strip()

# ─────────────────────────────────────────────
# Function: LLM as Judge
# ─────────────────────────────────────────────
def judge_answer(question, correct_slide_content, llm_answer):
    prompt = f"""You are an evaluator.
Slide content (ground truth): {correct_slide_content}
Student question: {question}
AI answer: {llm_answer}
Is the answer correct? Reply with ONLY: YES or NO."""
    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[{"role": "user", "content": prompt}],
        max_tokens=5,
    )
    verdict = response.choices[0].message.content.strip().upper()
    return "YES" in verdict

# ─────────────────────────────────────────────
# Evaluate all LLM models on first 20 questions
# ─────────────────────────────────────────────
test_sample = all_questions[:20]
llm_results = {}

for llm_name in llm_models:
    print(f"\n🔄 Testing LLM: {llm_name}")
    print("─" * 55)

    correct = 0
    total_tested = len(test_sample)

    for item in test_sample:
        question = item["question"]
        actual_slide_id = item["slide_id"]

        # Step 1: retrieve slide
        matched_slide = retrieve_best_slide(question)

        # Step 2: get correct slide content
        correct_slide = next((s for s in slides if s["slide_id"] == actual_slide_id), None)
        if not correct_slide:
            total_tested -= 1
            continue

        # Step 3: generate answer
        answer = get_llm_answer(question, matched_slide["content"], llm_name)

        # Step 4: judge
        is_correct = judge_answer(question, correct_slide["content"], answer)

        if is_correct:
            correct += 1

        status = "✅" if is_correct else "❌"
        print(f"{status} Q: {question[:60]}")
        print(f"   Retrieved: Slide {matched_slide['slide_id']} | Actual: Slide {actual_slide_id}")
        print(f"   Answer: {answer[:100]}\n")

    accuracy = correct / total_tested * 100
    llm_results[llm_name] = accuracy
    print(f"🎯 {llm_name} Accuracy: {accuracy:.1f}%")

# ─────────────────────────────────────────────
# Final comparison table
# ─────────────────────────────────────────────
print("\n📊 LLM Model Comparison Results:")
print("─" * 45)
print(f"{'LLM Model':<35} {'Accuracy':>8}")
print("─" * 45)
for name, acc in llm_results.items():
    print(f"{name:<35} {acc:>7.1f}%")
print("─" * 45)
